<?php

function setup_cli()
{
	require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'theme.inc';
	add_error_callback('cli_error_callback');
	
	// highjack request here!!
	if(dependency('run_from_cli') == true)
	{
		if(!isset($_REQUEST['path_info']))
			$_REQUEST['path_info'] = 'cli';
		$GLOBALS['settings']['local_template'] = 'cli';
		$GLOBALS['templates']['cli'] = array();
	}
}

function rewrite_cli($path_info, $request)
{
	// this is the bulk of the command line processing
	$request['path_info'] = $GLOBALS['argv'][1];
	
	foreach($GLOBALS['argv'] as $i => $value)
	{
		if(substr($value, 0, 2) == '--')
		{
			if(strpos($value, '=') !== false)
			{
				$name_value_pair = explode('=', substr($value, 2), 2);
				$name = trim($name_value_pair[0]);
				$request[$name] = trim($name_value_pair[1]);
			}
			else
			{
				$request[substr($value, 2)] = $GLOBALS['argv'][++$i];
			}
		}
	}
	
	if(validate($request, 'path_info') != 'cli')
		rewrite_vars($request, $get, $post);
	
	// get path information for privilage check
	$path = get_menu_entry($request['path_info']);
	$menu = $GLOBALS['menus'][$path];
	$module = get_module($menu['module']);
	
	// check access and prompt for password
	$user = session('users');
	if($module['privilage'] > $user['Privilage'])
	{
		// read in username
		print 'Login as: ';
		$request['username'] = trim(fgets(STDIN));
		print 'Password: ';
		$request['password'] = trim(fgets(STDIN));
	}
	
	return $request;
}

function setting_cli_columns($settings)
{
	if(isset($settings['cli_columns']) && is_numeric($settings['cli_columns']) &&
		$settings['cli_columns'] > 0
	)
		return $settings['cli_columns'];
	elseif(isset($_ENV['COLUMNS']))
		return $_ENV['COLUMNS'];
	elseif(($columns = exec('tput cols')))
		return $columns;
	else
		return 80;
}

function setting_cli_rows($settings)
{
	if(isset($settings['cli_rows']) && is_numeric($settings['cli_rows']) &&
		$settings['cli_rows'] > 0
	)
		return $settings['cli_rows'];
	elseif(isset($_ENV['ROWS']))
		return $_ENV['ROWS'];
	elseif(isset($_ENV['LINES']))
		return $_ENV['LINES'];
	elseif(($rows = exec('tput lines')))
		return $rows;
	else
		return 60;
}

function dependency_run_from_cli($settings)
{
	return (php_sapi_name() == 'cli');
}

function output_cli($request)
{
	// check if it is being run from the command line and display useful setting information
	if(isset($argv) && isset($argv[1]) && $argv[1] == '-conf')
	{
	}
	
}

function cli_error_callback($error)
{
	if($error->code & E_VERBOSE)
		return;
	
	if(substr($error->message, 0, 10) == 'PHP ERROR:')
		print cli_colorize(31);
	elseif(substr($error->message, 0, 9) == 'DB ERROR:')
		print cli_colorize(33);

	// get width from theme_stack
	$width = setting('cli_columns');
	// get the last call to the specified module's theme
	$result = false;
	for($i = count($GLOBALS['theme_stack'])-1; $i >=0; $i--)
	{
		$call = $GLOBALS['theme_stack'][$i];
		if(implements_theme($call['func']) == 'cli')
		{
			if(is_numeric($call['args'][count($call['args'])-1]))
			{
				$width = $call['args'][count($call['args'])-1];
				break;
			}
		}
	}

	print cli_wordwrap((isset($error->time)?('[' . $error->time . ']'):'') . $error->message, $width) . "\n";
	flush();
	
	if(substr($error->message, 0, 10) == 'PHP ERROR:' || substr($error->message, 0, 9) == 'DB ERROR:')
		cli_decolorize();
}
