<?php


function menu_list()
{
	return array(
		'list/%list' => array(
			'callback' => 'list_output',
		),
		'list/%list/%cat' => array(
			'callback' => 'list_output',
		),
		'list/%list/%cat/%item/%extra/%filename' => array(
			'callback' => 'list_output',
		),
	);
}

/**
 * Set up a list of different types of lists that can be outputted from any theme at any time
 * @ingroup setup
 */
function setup_list()
{
	include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'theme.inc';
	$GLOBALS['modules']['list']['lists'] = array(
		'rss' => array(
			'name' => 'RSS Feed',
			'file' => __FILE__,
			'encoding' => 'XML',
		),
		'xml' => array(
			'name' => 'XML List',
			'file' => __FILE__,
			'encoding' => 'XML',
		),
		'm3u' => array(
			'name' => 'M3U Playlist',
			'file' => __FILE__,
			'encoding' => 'TEXT',
		),
		'wpl' => array(
			'name' => 'Windows Media Playlist',
			'file' => __FILE__,
			'encoding' => 'XML',
		),
	);

	$GLOBALS['lists'] = &$GLOBALS['modules']['list']['lists'];
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return NULL by default, accepts any valid list name
 */
function validate_list($request)
{
	if(isset($request['list']) && in_array($request['list'], array_keys($GLOBALS['lists'])))
		return $request['list'];
}

/**
 * Implementation of output
 * @ingroup output
 */
function output_list($request)
{
	$request['cat'] = validate($request, 'cat');
	
	$request['list'] = validate($request, 'list');
	
	// if there isn't a list specified show the list template
	if(!isset($request['list']))
	{
		theme('list');
		
		return;
	}	
	else
	{
		header('Cache-Control: no-cache');
		if($request['list'] == 'rss')
		{
			header('Content-Type: application/rss+xml');
		}
		elseif($request['list'] == 'wpl')
		{
			header('Content-Type: application/vnd.ms-wpl');
		}
		else
		{
			header('Content-Type: ' . mime($request['list']));
		}
	
		// set some output variables
		register_output_vars('list', $request['list']);
		
		if(($session_select = session('select')))
		{
			$request['selected'] = $session_select['selected'];
		}
	
		// use the select.php module file selector to generate a list from the request
		//   should be the same list, and it will register the files output
		output_select($request);

		//   then the list template will be used
		theme($request['list']);
	}
}

