<?php

/** 
 * Implementation of setup_handler
 * @ingroup setup_handler
 */
function setup_audio()
{
	if(isset($GLOBALS['getID3']))
		return;
	
	// include the id handler
	include_once(include_path('getid3' . DIRECTORY_SEPARATOR . 'getid3.php'));
	
	// set up id3 reader incase any files need it
	$GLOBALS['getID3'] = new getID3();
}

/** 
 * Implementation of handles
 * @ingroup handles
 */
function handles_audio($file)
{
	$file = str_replace('\\', '/', $file);
	if(setting('admin_alias_enable')) $file = preg_replace($GLOBALS['alias_regexp'], $GLOBALS['paths'], $file);
	
	// get file extension
	$type = mime_type($file);
	
	if( $type == 'audio' )
	{
		return true;
	}

	return false;

}

function get_info_audio($file)
{
	$file = str_replace('/', DIRECTORY_SEPARATOR, $file);
	
	$info = $GLOBALS['getID3']->analyze($file);
	getid3_lib::CopyTagsToComments($info);
	
	if(!isset($info['comments_html']['title'][0])) $info['comments_html']['title'][0] = '';
	if(!isset($info['comments_html']['artist'][0])) $info['comments_html']['artist'][0] = '';
	if(!isset($info['comments_html']['album'][0])) $info['comments_html']['album'][0] = '';
	if(!isset($info['comments_html']['track'][0])) $info['comments_html']['track'][0] = 0;
	if(!isset($info['comments_html']['year'][0])) $info['comments_html']['year'][0] = '';
	if(!isset($info['comments_html']['genre'][0])) $info['comments_html']['genre'][0] = '';
	if(!isset($info['playtime_seconds'])) $info['playtime_seconds'] = 0;
	if(!isset($info['comments_html']['comments'][0])) $info['comments_html']['comments'][0] = '';
	if(!isset($info['bitrate'])) $info['bitrate'] = 0;

	$fileinfo = array();
	$fileinfo['Filepath'] = str_replace('\\', '/', $file);
	
	$fileinfo['Title'] = $info['comments_html']['title'][0];
	$fileinfo['Artist'] = $info['comments_html']['artist'][0];
	$fileinfo['Album'] = $info['comments_html']['album'][0];
	$fileinfo['Track'] = $info['comments_html']['track'][0];
	$fileinfo['Year'] = $info['comments_html']['year'][0];
	$fileinfo['Genre'] = $info['comments_html']['genre'][0];
	$fileinfo['Length'] = $info['playtime_seconds'];
	$fileinfo['Comments'] = $info['comments_html']['comments'][0];
	$fileinfo['Bitrate'] = $info['bitrate'];
	
	return $fileinfo;
}

