<?php

function menu_convert()
{
	return array(
		'convert/%convert' => array(
			'callback' => 'output_convert',
		),
	);
}

/**
 * Checks for convert path
 * @ingroup configure
 */
function configure_convert($settings)
{
	$settings['convert_path'] = setting('convert_path');
	
	$options = array();
	
	if(dependency('converter'))
	{
		$options['convert_path'] = array(
			'name' => lang('convert path title', 'Convert Path'),
			'status' => '',
			'description' => array(
				'list' => array(
					lang('convert path description 1', 'A converter has been set and detected, you may change this path to specify a new converter.'),
					lang('convert path description 2', 'The system needs some sort of image converter for creating thumbnails of images and outputting images as different file types.'),
					lang('convert path description 3', 'The converter detected is "' . basename($settings['convert_path']) . '".'),
				),
			),
			'type' => 'text',
			'value' => $settings['convert_path'],
		);
	}
	else
	{
		$options['convert_path'] = array(
			'name' => lang('convert path title', 'Convert Path'),
			'status' => 'fail',
			'description' => array(
				'list' => array(
					lang('convert path fail description 1', 'The system needs some sort of image converter for creating thumbnails of images and outputting images as different file types.'),
					lang('convert path fail description 2', 'This convert could be ImageMagik.'),
				),
			),
			'type' => 'text',
			'value' => $settings['convert_path'],
		);
	}
	
	$options['convert_args'] = array(
		'name' => lang('convert args title', 'Convert Arguments'),
		'status' => '',
		'description' => array(
			'list' => array(
				lang('convert args description 1', 'Specify the string of arguments to pass to the converter.'),
				lang('convert args description 2', 'Certain keys in the argument string will be replaced with dynamic values by the encode plugin:') . '<br />
				%IF - ' . lang('convert args input file', 'Input file, the filename that will be inserted for transcoding') . '<br />
				%FM - ' . lang('convert args format', 'Format to output') . '<br /> 
				%TH - ' . lang('convert args height', 'Thumbnail height') . '<br />
				%TW - ' . lang('convert args width', 'Thumbnail width') . '<br />
				%OF - ' . lang('convert args output file', 'Output file if necissary'),
			),
		),
		'type' => 'text',
		'value' => setting('convert_args'),
	);

	return array('convert' => array(
		'name' => 'Conversion Command',
		'type' => 'fieldset',
		'options' => $options
	));
}

/**
 * Implementation of status
 * @ingroup status
 */
function dependency_converter($settings)
{
	$settings['convert_path'] = setting('convert_path');
	return file_exists($settings['convert_path']);
}

/**
 * Implementation of setting
 * @ingroup setting
 * @return The default install path for VLC on windows or linux based on validate_SYSTEM_TYPE
 */
function setting_convert_path($settings)
{
	if(isset($settings['convert_path']) && is_file($settings['convert_path']))
		return $settings['convert_path'];
	else
	{
		if(setting_system_type($settings) == 'win')
		{
			if(file_exists('C:\Program Files (x86)\ImageMagick-6.4.9-Q16\convert.exe'))
				return 'C:\Program Files (x86)\ImageMagick-6.4.9-Q16\convert.exe';
			else
				return 'C:\Program Files\ImageMagick-6.4.9-Q16\convert.exe';
		}
		else
			return '/usr/bin/convert';
	}
}

/**
 * Implementation of setting
 * @ingroup setting
 * @return The entire arg string for further validation by the configure() function
 */
function setting_convert_args($settings)
{
	if(isset($settings['convert_args']) && is_file($settings['convert_args']))
		return $settings['convert_args'];
	else
	{
		if(setting_system_type($settings) == 'win')
			return '"%IF" %FM:-';
		else
			return '"%IF" -resize "%TWx%TH" %FM:-';
	}
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return jpg by default, jpg, gif, and png are valid
 */
function validate_convert($request)
{
	// set the header first thing so browser doesn't stall or get tired of waiting for the process to start
	if(isset($request['convert']))
	{
		$request['convert'] = strtolower($request['convert']);
		if($request['convert'] == 'jpg' || $request['convert'] == 'gif' || $request['convert'] == 'png')
		{
			return $request['convert'];
		}
	}
	return 'jpg';
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return jpeg by default, jpeg, gif, and png are valid
 */
function validate_cformat($request)
{
	if(!isset($request['cformat']))
	{
		$request['convert'] = validate($request, 'convert');
		switch($request['convert'])
		{
			case 'jpg':
				$request['cformat'] = 'jpeg';
				break;
			case 'gif':
				$request['cformat'] = 'gif';
				break;
			case 'png':
				$request['cformat'] = 'png';
				break;
		}
	}
	
	if(!in_array($request['cformat'], array('jpeg', 'gif', 'png')))
		return 'jpeg';
	else
		return $request['cformat'];
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return 512 by default, any number greater than zero is valid
 */
function validate_cheight($request)
{
	return generic_validate_numeric_default($request, 'cheight', 512);
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return 512 by default, any number greater than zero is valid
 */
function validate_cwidth($request)
{
	return generic_validate_numeric_default($request, 'cwidth', 512);
}

/**
 * Implementation of output
 * @ingroup output
 */
function output_convert($request)
{
	print 'hit';
	exit;
	set_time_limit(0);

	if(!isset($request['convert']))
	{
		theme('default');
		
		return;
	}
	
	// validate all the variables used
	$request['convert'] = validate($request, 'convert');
	$request['cheight'] = validate($request, 'cheight');
	$request['cwidth'] = validate($request, 'cwidth');
	$request['cformat'] = validate($request, 'cformat');
	$request['handler'] = validate($request, 'handler');
	$request['selected'] = validate($request, 'selected');

	// get the file path from the database
	$files = get_files($request, $count);

	if($count > 0)
	{
		// set height and width if it isn't already
		if(!isset($request['cheight']) && isset($files[0]['Height']))
			$request['cheight'] = $files[0]['Height'];
		
		if(!isset($request['cwidth']) && isset($files[0]['Width']))
			$request['cwidth'] = $files[0]['Width'];
		
		// set the file variable
		if(setting('alias_enable'))
			$request['cfile'] = alias_replace($files[0]['Filepath']);
		else
			$request['cfile'] = $files[0]['Filepath'];
	}
	else
	{
		raise_error('Image not found!', E_USER);
		
		theme('default');
		
		return;
	}
	// set the headers
	switch($request['convert'])
	{
		case 'jpg':
			header('Content-Type: image/jpg');
			break;
		case 'gif':
			header('Content-Type: image/gif');
			break;
		case 'png':
			header('Content-Type: image/png');
			break;
	}

	// close session so the client can continue browsing the site
	if(isset($_SESSION)) session_write_close();

	// if %IF is in the arguments and the file does not actually exist on disk
	//  then the file must be copied to a temporary location before converted
	if(strpos(setting('convert_args'), '%IF') !== false && $request['handler'] != 'files' &&
		module_implements('output', $request['handler'])
	)
	{
		$if = output_handler($request['cfile'], $request['handler']);
		$request['cfile'] = setting('tmp_dir') . 'convert_' . md5(microtime());
		$of = fopen($request['cfile'], 'wb');
		
		output_stream($if, $of);
	}

	// replace the argument string with the contents of $_REQUEST
	//  without validation this is VERY DANGEROUS!
	$cmd = basename(setting('convert_path')) . ' ' . str_replace(array(
		'%TH', 
		'%TW', 
		'%IF', 
		'%FM'
	), array(
		$request['cheight'], 
		$request['cwidth'], 
		$request['cfile'], 
		$request['cformat']
	), setting('convert_args'));

	// run process and output binary from pipe
	$descriptorspec = array(
	   0 => array("pipe", "r"),  // stdin is a pipe that the child will read from
	   1 => array("pipe", "w"),  // stdout is a pipe that the child will write to
	   2 => array("pipe", "w"),  // stderr is a pipe that the child will write to
	);

	$process = proc_open($cmd, $descriptorspec, $pipes, dirname(setting('convert_path')), NULL, array('binary_pipes' => true));

	// output file
	if(strpos(setting('convert_args'), '%IF') !== false)
	{
		$of = fopen('php://output', 'wb');
		
		if(is_resource($process))
		{
			output_stream($pipes[1], $of);
			
			$status = proc_get_status($process);
			kill9('convert', $status['pid']);
		
			$return_value = proc_close($process);
		}
		
		// remove temporary file
		if($request['handler'] != 'files' && module_implements('output', $request['handler']))
			unlink($request['cfile']);
	}
}
