<?php


function bootstrap_search($module)
{
	$columns = get_columns($module);
	foreach($columns as $column)
	{
		$GLOBALS['validate_search_' . $column] = create_function('$request', 'return validate_search($request, \'' . $column . '\');');
	}
}

/**
 * Implementation of dependency
 * @ingroup dependency
 */
function dependency_search($settings)
{
	if(dependency('alias') != false)
		return array('database', 'alias');
	else
		return array('database');
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return NULL by default, returns any search query, this is validated in the alter_query instead of here
 */
function validate_search($request, $column = 'ALL')
{
	if($column == 'ALL' && isset($request['search']))
		return $request['search'];
	if(isset($request['search_' . $column]))
	{
		// validated in handlers when used
		return $request['search_' . $column];
	}
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return NULL by default, accepts 'AND' or 'OR'
 */
function validate_search_operator($request)
{
	if(isset($request['search_operator']) && ($request['search_operator'] == 'AND' || $request['search_operator'] == 'OR'))
		return $request['search_operator'];
}

/**
 * Implementation of session
 * Saves the previous search information for references
 * @ingroup session
 */
function session_search($request)
{
	if(isset($_POST['clear_search']) || isset($_GET['clear_search']))
		return array();

	// store this query in the session
	$save = array();
	if(isset($request['cat'])) $save['cat'] = $request['cat'];
	if(isset($request['search'])) $save['search'] = $request['search'];
	foreach($request as $key => $value)
	{
		if(substr($key, 0, 7) == 'search_')
			$save[$key] = $value;
	}
	if(isset($request['dir'])) $save['dir'] = $request['dir'];
	if(isset($request['order_by'])) $save['order_by'] = $request['order_by'];

	return $save;
}

/**
 * Determines the type of search a user would like to perform based on the surrounding characters
 * @param search the search query for any column
 * @return 'normal' by default indicating the search string should be tokenized and read for '+' required tokens, '-' excluded tokens, and optional include tokens
 * 'literal' if the search string is surrounded by double quotes
 * 'equal' if the search string is surrounded by equal signs
 * 'regular' for regular expression if the search is surrounded by forward slashes
 */
function search_get_type($search)
{
	if(strlen($search) > 1 && $search[0] == '"' && $search[strlen($search)-1] == '"')
		return 'literal';
	elseif(strlen($search) > 1 && $search[0] == '=' && $search[strlen($search)-1] == '=')
		return 'equal';
	elseif(strlen($search) > 1 && $search[0] == '/' && $search[strlen($search)-1] == '/')
		return 'regular';
	else
		return 'normal';
}

/**
 * For a normal search, get each piece that may be preceeded with a '+' for require or a '-' for exclude
 * @param search the search string
 * @return an associative array containing:
 * 'length' of the query string
 * 'count' of all the pieces
 * 'required' all the pieces preceeded by a '+' in the query string
 * 'excluded' all the pieces to be excluded preceeded by a '-'
 * 'includes' all the pieces that should contain at least 1 include
 */
function search_get_pieces($search)
{
	// loop through search terms and construct query
	$pieces = explode(' ', $search);
	$pieces = array_unique($pieces);
	$empty = array_search('', $pieces, true);
	if($empty !== false) unset($pieces[$empty]);
	$pieces = array_values($pieces);
	
	// sort items by inclusive, exclusive, and string size
	// rearrange pieces, but keep track of index so we can sort them correctly
	uasort($pieces, 'termSort');
	$length = strlen(join(' ', $pieces));
	
	// these are the 3 types of terms we can have
	$required = array();
	$excluded = array();
	$includes = array();

	foreach($pieces as $j => $piece)
	{
		if($piece[0] == '+')
			$required[$j] = substr($piece, 1);
		elseif($piece[0] == '-')
			$excluded[$j] = substr($piece, 1);
		else
			$includes[$j] = $piece;
	}
	
	return array(
		'length' => $length,
		'count' => count($pieces),
		'required' => $required,
		'excluded' => $excluded,
		'includes' => $includes
	);
}

/**
 * Generate an SQL query from the pieces
 * @param pieces The pieces from search_get_pieces()
 * @return an associative array of properties of the SQL query, containing COLUMNS, ORDER, and WHERE
 */
function search_get_pieces_query($pieces)
{
	$columns = '';
	
	$required = '';
	$excluded = '';
	$includes = '';
	
	foreach($pieces['required'] as $j => $piece)
	{
		if($required != '') $required .= ' AND ';
		$required .= 'LOCATE("' . addslashes($piece) . '", {column}) > 0';
		$columns .= '(LOCATE("' . addslashes($piece) . '", {column}) > 0)+';
	}
	
	foreach($pieces['excluded'] as $j => $piece)
	{
		if($excluded != '') $excluded .= ' AND ';
		$excluded .= 'LOCATE("' . addslashes($piece) . '", {column}) = 0';
		$columns .= '(LOCATE("' . addslashes($piece) . '", {column}) = 0)+';
	}
	
	foreach($pieces['includes'] as $j => $piece)
	{
		if($includes != '') $includes .= ' OR ';
		$includes .= 'LOCATE("' . addslashes($piece) . '", {column}) > 0';
		$columns .= '(LOCATE("' . addslashes($piece) . '", {column}) > 0)+';
	}
	
	// add parenthesis to each part
	if($required != '') $required = '(' . $required . ')';
	if($excluded != '') $excluded = '(' . $excluded . ')';
	if($includes != '') $includes = '(' . $includes . ')';
	
	// remove trailing comma
	if($columns != '')
		$columns = '(' . substr($columns, 0, -1) . ')';
	
	$part = '';
	$part .= (($required != '')?(($part != '')?' AND ':'') . $required:'');
	$part .= (($excluded != '')?(($part != '')?' AND ':'') . $excluded:'');
	$part .= (($includes != '')?(($part != '')?' AND ':'') . $includes:'');
	
	return array(
		'columns' => $columns,
		'where' => $part,
	);
}

/**
 * Implementation of alter_query
 * Alter a database queries when the search variable is set in the request
 * @ingroup alter_query
 */
function filter_search($request)
{
	// do not alter the query if selected is set
	$request['selected'] = validate($request, 'selected');
	if(!empty($request['selected']))
		return;
	
	// some other variables we need
	$request['order_by'] = validate($request, 'order_by');
	
	// they can specify multiple columns to search for the same string
	if(isset($request['columns']))
	{
		$columns = explode(',', $request['columns']);
	}
	// search every column for the same string
	else
	{
		$columns = get_columns(validate($request, 'handler'));
	}
		
	// array for each column
	$parts = array();
	
	$result = array();
	
	// loop through each column to compile search query
	foreach($columns as $i => $column)
	{
		if(isset($request['search_' . $column]) && $request['search_' . $column] != '')
			$search = $request['search_' . $column];
		elseif(isset($request['search']) && $request['search'] != '')
			$search = $request['search'];
		else
			continue;

		$type = search_get_type($search);
		
		// remove characters on either side of input
		if($type != 'normal')
			$search = substr($search, 1, -1);
		
		// incase an aliased path is being searched for replace it here too!
		if(setting('alias_enable'))
			$search = alias_replace($search);
		
		if($type == 'normal')
		{
			$pieces = search_get_pieces($search);
			$query = search_get_pieces_query($pieces);
		}
		
		// tokenize input
		if($type == 'normal')
		{
			$replaced = str_replace(array('{column}', '{column_index}'), array($column, $i), $query);
			$parts[] = $replaced['where'];
			$result['columns'] = (isset($result['columns'])?($result['columns'] . '+'):'') . $replaced['columns'];
			
			$result['columns'] .= '*10-ABS(LENGTH(' . $column . ') - ' . $pieces['length'] . ')';
		}
		elseif($type == 'equal')
		{
			$parts[] = $column . ' = "' . addslashes($search) . '"';
		}
		elseif($type == 'regular')
		{
			$parts[] = $column . ' REGEXP "' . addslashes($search) . '"';
		}
		elseif($type == 'literal')
		{
			$parts[] = ' LOCATE("' . addslashes($search) . '", ' . $column . ')';
		}
	}
	
	// remove leading commas
	if(!empty($result['columns']))
	{
		$result['columns'] .= ' AS Relevance';
		$result['order'] = 'Relevance DESC';
	}
	
	// set the new props
	if(count($parts) > 0)
	{
		$result['where'] = join((isset($request['search_operator'])?(' ' . $request['search_operator'] . ' '):' OR '), $parts);
	}
		
	return $result;
}

/**
 * Implementation of output
 * @ingroup output
 */
function output_search($request)
{
	// output search information
	if(($session_search = session('search')))
		register_output_vars('search', $session_search);

	// replace search results with highlight
	$search_regexp = array();

	// get columns being searched
	$columns = get_columns($request['handler']);
	
	$all_columns = get_all_columns();
	
	// replace each column with search match
	foreach($all_columns as $i => $column)
	{
		if(in_array($column, $columns))
		{
			// select input for individual columns
			if(isset($GLOBALS['output']['search']['search_' . $column]))
				$query = $GLOBALS['output']['search']['search_' . $column];
			else
				$query = isset($GLOBALS['output']['search']['search'])?$GLOBALS['output']['search']['search']:'';
				
			// replace with search
			if(substr($query, 0, 1) == '/' && substr($query, -1) == '/')
			{
				$search_regexp[$column] = $query . 'ie';
			}
			elseif(substr($query, 0, 1) == '"' && substr($query, -1) == '"')
			{
				$search_regexp[$column] = '/' . substr($query, 1, strlen($query) - 2) . '/ie';
			}
			elseif(substr($query, 0, 1) == '=' && substr($query, -1) == '=')
			{
				$search_regexp[$column] = '/^' . substr($query, 1, strlen($query) - 2) . '$/ie';
			}
			else
			{
				$tmp_parts = array_unique(explode(' ', stripslashes($query)));
				$search_regexp[$column] = array();
				foreach($tmp_parts as $i => $part)
				{
					if($part != '')
					{
						if($part[0] == '+') $part = substr($part, 1);
						$search_regexp[$column][] = '/' . preg_quote($part) . '/ie';
					}
				}
			}
		}
		else
		{
			$search_regexp[$column] = '//e';
		}
	}
	register_output_vars('search_regexp', $search_regexp);
}
