<?php


function menu_sitemap()
{
	return array(
		'robots.txt' => array(
			'callback' => 'output_robots',
			'type' => MENU_CALLBACK,
		),
		'sitemap.xml' => array(
			'callback' => 'output_sitemap',
		)
	);
}

function setup_sitemap()
{
	// just incase the robots to not honor the bots.txt, rewrite them here
	if(setting('no_bots'))
	{
		// do not let GoogleBot perform searches or file downloads
		if(setting('agent_simple') == 'googlebot')
		{
			if(basename($_REQUEST['path_info']) != 'sitemap.xml')
			{
				$_REQUEST['path_info'] = 'sitemap.xml';
			}
			else
			{
				// don't let google bots perform searches, this takes up a lot of resources
				foreach($_REQUEST as $key => $value)
				{
					if(substr($key, 0, 6) == 'search')
					{
						unset($_REQUEST[$key]);
					}
				}
			}
		}
	}
}


/**
 * Implementation of setting
 * @ingroup setting
 * @return true by default
 */
function setting_no_bots($settings)
{
	return (!isset($settings['no_bots']) || filter_var($settings['no_bots'], FILTER_VALIDATE_BOOLEAN));
}


function configure_sitemap($settings)
{
	$settings['no_bots'] = setting('no_bots');
	
	$options['setting_no_bots'] = array(
		'name' => lang('Robots Handling', 'no bots title'),
		'status' => '',
		'description' => array(
			'list' => array(
				lang('Some services like Google like to scan websites.  This option will prevent robots from downloading and scanning files on your site.', 'no bots description 1'),
				lang('This will also enable robots to view a customizable sitemap.php module that provides them with the information they deserve.', 'no bots description 2'),
			),
		),
		'type' => 'boolean',
		'value' => $settings['no_bots'],
		'options' => array(
			lang('Disable Robots', 'no bots option 1'),
			lang('Allow Robots to Scan my Files', 'no bots option 2'),
		)
	);
	
	return array('sitemap' => array(
		'name' => 'Sitemap Settings',
		'type' => 'fieldset',
		'options' => $options,
	));
}

function output_robots($request)
{
	if(setting('no_bots'))
	{
		header('Content-Type: text/plain');
		print "User-agent: *
Disallow: /
";
	}
}


function output_sitemap($request)
{
}