<?php

include dirname(__FILE__) . DIRECTORY_SEPARATOR . 'theme.php';

function theme_tunegazelle_header($title)
{
	?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php theme('redirect_block'); ?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php print setting('html_name'); ?></title>
<meta name="google-site-verification" content="K3Em8a7JMI3_1ry5CNVKIHIWofDt-2C3ohovDq3N2cQ" />
<script type="text/javascript" src="<?php print url('template/tunegazelle/scripts'); ?>"></script>
<link rel="stylesheet" href="<?php print url('template/tunegazelle/styles'); ?>" type="text/css"/>
<script type="text/javascript">
	$(document).ready(function() {
		resize_panels();
	});
	$(window).resize(resize_panels);
	function resize_panels() {
		$('#left-menu').height($(window).height() - $('#left-menu').offset().top);
	}
</script>
</head>
<body>
	<div id="heading"><h1><?php print setting('html_name'); ?></h1></div>
	<div id="left-menu">
		<div id="inner-list">
			<ul>
				<li><?php print lang('My Files', 'my files'); ?></li>
			</ul>
		</div>
	</div>
	<?php
}


function theme_tunegazelle_select()
{
	theme('header');

	?>
	<?
}


function theme_tunegazelle_footer()
{
	?></body>
	</html>
	
	<?php
}


function theme_tunegazelle_styles()
{
	header("Cache-Control: cache");  
	header("Pragma: public");
	header('Content-Type: text/css');
	$styles = array('styles/layout.css');
	
	foreach($styles as $i => $style)
	{
		print file_get_contents(dirname(__FILE__) . DIRECTORY_SEPARATOR . $style);
	}
	
	tunegazelle_colors();
}


function theme_tunegazelle_scripts()
{
	header("Cache-Control: cache");  
	header("Pragma: public");
	header('Content-Type: text/javascript');
	$scripts = array('js/jquery.js', 'js/jquery-ui.js');
	
	foreach($scripts as $i => $script)
	{
		print file_get_contents(dirname(__FILE__) . DIRECTORY_SEPARATOR . $script);
	}
}

