<?php


/**
 * Implementation of setup_handler
 * @ingroup setup_handler
 */
function setup_video()
{
	if(isset($GLOBALS['getID3']))
		return;
		
	// include the id handler
	load_include('getid3' . DIRECTORY_SEPARATOR . 'getid3.php');
	
	// set up id3 reader incase any files need it
	$GLOBALS['getID3'] = new getID3();
}

/**
 * Implementation of handles
 * @ingroup handles
 */
function handles_video($file)
{
	// get file extension
	$type = mime_type($file);
	
	if( $type == 'video' )
	{
		return true;
	}

	return false;

}

/**
 * Helper function
 */
function get_info_video($file)
{
	$info = $GLOBALS['getID3']->analyze($file);
	getid3_lib::CopyTagsToComments($info);
	
	if(!isset($info['comments_html']['title'][0])) $info['comments_html']['title'][0] = '';
	if(!isset($info['comments_html']['comments'][0])) $info['comments_html']['comments'][0] = '';
	if(!isset($info['bitrate'])) $info['bitrate'] = 0;
	if(!isset($info['playtime_seconds'])) $info['playtime_seconds'] = 0;
	if(!isset($info['audio']['channels'])) $info['audio']['channels'] = 0;
	if(!isset($info['audio']['bitrate'])) $info['audio']['bitrate'] = 0;
	if(!isset($info['video']['bitrate'])) $info['video']['bitrate'] = 0;
	if(!isset($info['video']['resolution_x'])) $info['video']['resolution_x'] = 0;
	if(!isset($info['video']['resolution_y'])) $info['video']['resolution_y'] = 0;
	if(!isset($info['video']['frame_rate'])) $info['video']['frame_rate'] = 0;
	
	$fileinfo = array();
	$fileinfo['Filepath'] = str_replace(DIRECTORY_SEPARATOR, '/', $file);
	
	$fileinfo['Title'] = $info['comments_html']['title'][0];
	$fileinfo['Comments'] = $info['comments_html']['comments'][0];
	$fileinfo['Bitrate'] = $info['bitrate'];
	$fileinfo['Length'] = $info['playtime_seconds'];
	$fileinfo['Channels'] = $info['audio']['channels'];
	$fileinfo['AudioBitrate'] = $info['audio']['bitrate'];
	$fileinfo['VideoBitrate'] = $info['video']['bitrate'];
	$fileinfo['Resolution'] = $info['video']['resolution_x'] . 'x' . @$info['video']['resolution_y'];
	$fileinfo['FrameRate'] = $info['video']['frame_rate'];
	
	return $fileinfo;
}

