<?php

function menu_tools()
{
	return array(
		'admin/tools' => array(
			'type' => MENU_LIST,
		),
	);
}

function setup_tools()
{
	require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'theme.inc';
}

function setting_tools()
{
	return array();
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return False by default
 */
function validate_info_singular($request)
{
	if(!isset($request['info_singular']))
		return false;
	else
		return filter_var($request['info_singular'], FILTER_VALIDATE_BOOLEAN);
}
