<?php

function menu_tools()
{
	return array(
		'admin/tools' => array(
			'type' => MENU_LIST,
			'name' => $GLOBALS['modules']['tools']['name'],
			'description' => $GLOBALS['modules']['tools']['description'],
			'callback' => 'output_menu',
			'module' => 'menu',
		),
	);
}

function setup_tools()
{
	require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'theme.inc';
	$GLOBALS['modules']['tools']['tools'] = load_modules(dirname(__FILE__) . DIRECTORY_SEPARATOR);
}

/**
 * Implementation of validate
 * @ingroup validate
 * @return False by default
 */
function validate_info_singular($request)
{
	return generic_validate_boolean_false($request, 'info_singular');
}
