<?php

function setting_download_services_torservices()
{
	return array('torservice_0', 'torservice_1', 'torservice_2', 'torservice_3');
}

function setting_torservice_0($settings)
{
	return array(
		'name' => 'What.CD',
		'match' => '/<a href="(torrents.php?action=download[^"]*?)"/i',
		'search' => '',
		'login' => 'http://what.cd/login.php',
		'loginfail' => '<span class="warning">',
		'exclude' => 'keeplogged'
	);
}

function setting_torservice_1($settings)
{
	return array(
		'name' => 'Waffles.FM',
		'match' => '/<a href="(\/download.php\/[^"]*?)"/i',
		'search' => '',
		'login' => 'https://www.waffles.fm/w/index.php?title=Special%3AUserLogin&returnto=Main_Page',
		'userfield' => 'wpName',
		'passfield' => 'wpPassword',
		'loginfail' => '/<h2>Login error<\/h2>/i',
		'exclude' => 'wpMailmypassword,autoLogout,useSSL',
	);
}

function setting_torservice_2($settings)
{
	return array(
		'name' => 'TvTorrents',
		'match' => '/<a href="" onclick="return loadTorrent\(\'([^\']*?)\'/i',
		'search' => '',
		'login' => 'http://tvtorrents.com/',
		'loginfail' => '/<font class="error">/i',
		'exclude' => 'cookie'
	);
}

function setting_torservice_3($settings)
{
	return array(
		'name' => 'TheDvdClub',
		'match' => '/<a id="hltorrent9546" href="([^"]*)"/i',
		'search' => '',
		'login' => 'http://thedvdclub.org/login.php',
		'loginfail' => '/color="red">Error:/i',
		'exclude' => 'cookie'
	);
}

/**
 * Implementation of setting
 * @ingroup setting
 */
function setting_torpath($settings)
{
	if(isset($settings['torpath']) && is_dir($settings['torpath']))
		return $settings['torpath'];
	else
		return '';
}
	
/**
 * Implementation of configure
 * @ingroup configure
 */
function configure_torservices($settings)
{
	$settings['torpath'] = setting('torpath');
	
	$options = array();
	
	if($settings['torpath'] == '' || is_writable($settings['torpath']))
	{
		$options['setting_torpath'] = array(
			'name' => 'Torrent Save path',
			'status' => '',
			'description' => array(
				'list' => array(
					'Select a path to save the torrent files to.',
					'Some torrent clients such as uTorrent can automatically search a directory for new torrent files.'
				),
			),
			'type' => 'text',
			'value' => $settings['torpath'],
		);
	}
	else
	{
		$options['setting_torpath'] = array(
			'name' => 'Torrent Save path',
			'status' => 'fail',
			'description' => array(
				'list' => array(
					'The selected path is not writable!',
					'Select a path to save the torrent files to.',
					'Some torrent clients such as uTorrent can automatically search a directory for new torrent files.'
				),
			),
			'type' => 'text',
			'value' => $settings['torpath'],
		);
	}
	
	return array('torservices' => array(
		'name' => 'Torrenting Services',
		'type' => 'fieldset',
		'options' => $options
	));
}
