<?php


function menu_music_download()
{
	return array(
		'admin/tools/music/downloader' => array(
			'callback' => 'output_music_download',
		),
		'admin/tools/music/downloader/%music_download_mode/%service_index' => array(
			'callback' => 'output_music_download'
		),
	);
}

function validate_music_download_mode($request)
{
	if(isset($request['music_download_mode']) && in_array($request['music_download_mode'], array('login', 'search')))
		return $request['music_download_mode'];
}

function setup_music_download()
{
	require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'msdl.singular.inc';
}

function setting_music_formats($settings)
{
	if(isset($settings['music_formats']))
	{
		$formats = explode(',', $settings['music_formats']);
		$valid = array();
		foreach($formats as $i => $format)
		{
			$format = generic_validate_all_safe(array('format' => $format), 'format');
			if(isset($format))
				$valid[] = $format;
		}
		return implode(',', $valid);
	}
	return 'MP3 V0 VBR,MP3 320,FLAC LOSSLESS,MP3';
}

function configure_music_download($settings)
{
	$options = array();
	
	$options['setting_music_formats'] = array(
		'name' => 'Preffered Format',
		'status' => '',
		'description' => array(
			'list' => array(
				'Enter the formats in the order in which you would like them selected and automatically downloaded, seperate by commas.',
				'Example: V0,FLAC,MP3 320,MP3',
			),
		),
		'type' => 'text',
		'values' => setting('music_formats'),
	);
	
	return array('music_download' => array(
		'name' => 'Format Selection',
		'type' => 'fieldset',
		'options' => $options
	));
}

/**
 * Implementation of output
 * @ingroup output
 */
function output_music_download($request)
{
	$request['music_download_mode'] = validate($request, 'music_download_mode');
	
	if(!isset($request['music_download_mode']))
	{
		// output configuration link
		raise_error(array(
			'You may need to ',
			'link' => array(
				'url' => 'admin/module/music_download',
				'text' => 'configure'
			),
			' this tool in order to use it properly.'
		), E_WARN);
			
		// perform logins
		$infos = get_download_services_login(NULL, 'admin/tools/music/downloader/login/');
			
		// output info
		register_output_vars('infos', array(
			'music_downloader' => array(
				'name' => 'Music Downloader',
				'type' => 'fieldset',
				'options' => $infos
			),
		));
		
		theme('tool_info');
		
		return;
	}
	
	$infos = array();
	
	if($request['music_download_mode'] == 'login')
	{
		$request['service_index'] = validate($request, 'service_index');
		$request['service_search'] = session('download_services');
		
		$infos = get_download_services_login($request['service_index'], 'admin/tools/music/downloader/login/');

		if($request['service_index'] == count(setting('all_download_services'))-1)
		{
			$request['service_index'] = 0;
			$request['music_download_mode'] = 'search';
		}
	}
	
	if($request['music_download_mode'] == 'search')
	{
		$artists = db_assoc('SELECT * FROM audio GROUP BY Artist');
		
		foreach($artists as $i => $artist)
		{
			session('download_services', $artist['Artist']);
			$request['service_index'] = validate($request, 'service_index');
			$request['service_search'] = session('download_services');
			
			$infos = array_merge($infos, get_download_services_manual($request['service_index'], $request['service_search'], 'audio', 'admin/tools/music/downloader/search/'));
	
			if(!empty($request['service_search']) && $request['service_index'] == count(setting('all_download_services', 'audio'))-1)
			{
				$infos = array_merge($infos, get_music_download_manual($request));
			}
		}
	}
	
	theme('form_fieldrows', $infos);

}
