<?php


function menu_music_download()
{
	return array(
		'admin/tools/music/downloader' => array(
			'callback' => 'output_music_download',
		),
		'admin/tools/music/downloader/%info_singular_step_music' => array(
			'callback' => 'output_music_download_singular'
		)
	);
}

function setup_music_download()
{
	require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'msdl.singular.inc';
}

/**
 * Set up the list of settings
 * @ingroup setup
 */
function setting_music_download()
{
	$settings = array('');
	
	// add wrapper functions for nzb_movie_search
	for($i = 0; $i < 10; $i++)
	{
		$GLOBALS['setting_nzb_music_search_' . $i] = create_function('$settings', 'return setting_nzb_music_search($settings, \'' . $i . '\');');
		$settings[] = 'nzb_movie_search_' . $i;
	}
	
	// add wrapper functions for tor_movie_search
	for($i = 0; $i < 10; $i++)
	{
		$GLOBALS['setting_tor_music_search_' . $i] = create_function('$settings', 'return setting_tor_music_search($settings, \'' . $i . '\');');
		$settings[] = 'tor_movie_search_' . $i;
	}
	
	return $settings;
}

/**
 * Implementation of setting
 * @ingroup setting
 */
function setting_nzb_music_search($settings, $index)
{
	// return the same static service as listed in the nzbservice module
	if($index == 0)
		return 'http://nzbmatrix.com/nzb-search.php?cat=22&search=%s';
	if($index == 1)
		return 'http://www.newzbin.com/search/query/?searchaction=Go&group=alt.binaries.sounds.mp3.complete_cd&q=%s';

	// don't continue with this if stuff is missing
	if(isset($settings['nzb_music_search_' . $index]) && 
		$settings['nzb_music_search_' . $index] != ''
	)
		return $settings['nzb_music_search_' . $index];
	// use default
	elseif(isset($settings['nzbservice_' . $index]['search']) && 
		$settings['nzbservice_' . $index]['search'] != ''
	)
		return $settings['nzbservice_' . $index]['search'];
}

/**
 * Implementation of setting
 * @ingroup setting
 */
function setting_tor_music_search($settings, $index)
{
	// the static services to not have movies, only tv and music
	if($index == 0)
		return 'http://what.cd/torrents.php?searchstr=%s';
	if($index == 1)
		return 'https://www.waffles.fm/browse.php?q=%s';
	if($index == 2 || $index == 3)
		return '';

	// don't continue with this if stuff is missing
	if(isset($settings['tor_music_search_' . $index]) && 
		$settings['tor_music_search_' . $index] != ''
	)
		return $settings['tor_music_search_' . $index];
	// use default
	elseif(isset($settings['torservice_' . $index]['search']) && 
		$settings['torservice_' . $index]['search'] != ''
	)
		return $settings['torservice_' . $index]['search'];
}
