<?php
include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'select.php';
include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'users.php';
include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'search.php';

include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'header.php';
include_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'footer.php';

function theme_live_logo()
{
	$result = fetch('http://www.monolithicmedia.org/favicon.ico', array(), array('timeout' => 2));
	if(isset($result['headers']['Content-Type']))
		header('Content-Type: ' . $result['headers']['Content-Type']);
	print $result['content'];
}

function validate_live($request)
{
	if(!isset($request['dir']))
		$request['dir'] = '/';
	
	if(!isset($request['limit']))
		$request['limit'] = 50;
}

function live_get_info_count()
{
	$biggest = 0;
	if(!isset($GLOBALS['output']['files'])) return $biggest;
	foreach($GLOBALS['output']['files'] as $file)
	{
		$info_count = 0;
		foreach($GLOBALS['output']['columns'] as $column)
		{
			if(isset($file[$column]) && $file[$column] != '' && strlen($file[$column]) <= 200 &&
				substr($column, -3) != '_id' && $column != 'id' && $column != 'Hex' && $column != 'Filename' && $column != 'Filetype')
			$info_count++;
		}
		
		$info_count = ceil($info_count/2);
		if($info_count > $biggest) $biggest = $info_count;
	}
	
	return $biggest;
}

function live_alter_file($file)
{
	foreach($file as $column => $value)
	{
		if($column == 'Filepath')
		{
			$dirs = explode('/', $file['Filepath']);
			if($dirs[0] == '' || $dirs[0] == dirname(realpath('/')))
				array_shift($dirs);
			array_walk($dirs, create_function('&$item,$key', '$item = urlencode($item);'));
			$file['Filepath'] = implode('/', $dirs);
		}
		elseif(isset($GLOBALS['output']['search_regexp']) && 
			isset($GLOBALS['output']['search_regexp'][$column])
		)
		{
			$file[$column] = preg_replace($GLOBALS['output']['search_regexp'][$column], '\'<strong style="background-color:#990;">\' . htmlspecialchars(\'$0\') . \'</strong>\'', $file[$column]);
		
			continue;
		}
		//$file[$column] = preg_replace('/([^ ]{25})/i', '$1<br />', $file[$column]);
		elseif($column == 'Filesize')
			$file['Filesize'] = roundFileSize($file['Filesize']);
		elseif($column == 'Compressed')
			$file['Compressed'] = roundFileSize($file['Compressed']);
		elseif($column == 'Bitrate')
			$file['Bitrate'] = round($file['Bitrate'] / 1000, 1) . ' kbs';
		elseif($column == 'Length')
			$file['Length'] = floor($file['Length'] / 60) . ' minutes ' . floor($file['Length'] % 60) . ' seconds';
		else
			$file[$column] = htmlspecialchars($value);
	}
	return $file;
}

function theme_live_pages()
{
	// set some variables if they are missing so we can avoid errors
	if(!isset($GLOBALS['output']['start']))
		$GLOBALS['output']['start'] = 0;
	if(!isset($GLOBALS['output']['total_count']))
		$GLOBALS['output']['total_count'] = 0;
	if(!isset($GLOBALS['output']['limit']))
		$GLOBALS['output']['limit'] = 50;

	?>
	<table cellpadding="0" cellspacing="0" class="pageTable">
		<tr>
			<td align="center">
				<table cellpadding="0" cellspacing="0">
					<tr>
						<td>
	<?php
	if(!isset($GLOBALS['output']['files']))
		$item_count = 0;
	else
		$item_count = count($GLOBALS['output']['files']);
	$page_int = $GLOBALS['output']['start'] / $GLOBALS['output']['limit'];
	$lower = $page_int - 8;
	$upper = $page_int + 8;
	$GLOBALS['output']['total_count']--;
	$pages = floor($GLOBALS['output']['total_count'] / $GLOBALS['output']['limit']);
	$prev_page = $GLOBALS['output']['start'] - $GLOBALS['output']['limit'];
	if($pages > 0)
	{
		if($lower < 0)
		{
			$upper = $upper - $lower;
			$lower = 0;
		}
		if($upper > $pages)
		{
			$lower -= $upper - $pages;
			$upper = $pages;
		}
		
		if($lower < 0)
			$lower = 0;
		
		if($GLOBALS['output']['start'] > 0)
		{
			if($GLOBALS['output']['start'] > $GLOBALS['output']['limit'])
			{
			?>
			<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
				<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=0'); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">First</a>
			</div>
			<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
				<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=' . $prev_page); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">Prev</a>
			</div>
			<?php
			}
			else
			{
			?>
			<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
				<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=0'); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">First</a>
			</div>
			<?php
			}
			?><div class="page">|</div><?php
		}
		
		for($i = $lower; $i < $upper + 1; $i++)
		{
			if($i == $page_int)
			{
				?><div class="page<?php print (strlen($i) > 2)?'W':''; ?>"><b><?php print $page_int + 1; ?></b></div><?
			}
			else
			{
				?>
				<div class="page<?php print (strlen($i) > 2)?'W':''; ?>"><div class="pageHighlight<?php print (strlen($i) > 2)?'W':''; ?>" style="visibility:hidden"></div>
					<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=' . ($i * $GLOBALS['output']['limit'])); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;"><?php print $i + 1; ?></a>
				</div>
				<?php
			}
		}
		
		if($GLOBALS['output']['start'] <= $GLOBALS['output']['total_count'] - $GLOBALS['output']['limit'])
		{
			?><div class="page">|</div><?php
			$last_page = floor($GLOBALS['output']['total_count'] / $GLOBALS['output']['limit']) * $GLOBALS['output']['limit'];
			$next_page = $GLOBALS['output']['start'] + $GLOBALS['output']['limit'];
			if($GLOBALS['output']['start'] < $GLOBALS['output']['total_count'] - 2 * $GLOBALS['output']['limit'])
			{
				?>
				<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
					<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=' . $next_page); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">Next</a>
				</div>
				<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
					<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=' . $last_page); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">Last</a>
				</div>
				<?php
			}
			else
			{
				?>
				<div class="pageW"><div class="pageHighlightW" style="visibility:hidden"></div>
					<a class="pageLink" href="<?php print url($GLOBALS['output']['get'] . '&start=' . $last_page); ?>" onmouseout="this.parentNode.firstChild.style.visibility = 'hidden'; return true;" onmouseover="this.parentNode.firstChild.style.visibility = 'visible'; return true;">Last</a>
				</div>
				<?php
			}
		}
	}
	?>
	
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
 <?php
}
